AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: "Course4Resources"
Resources:
    LoadBalancer01:
      Type: AWS::ElasticLoadBalancing::LoadBalancer
      Properties:
        AvailabilityZones:
        - "us-east-1a"
        Instances:
        - Ref: EC2Instance
        - Ref: EC2Instance2
        Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
        HealthCheck:
          Target: HTTP:80/
          HealthyThreshold: '3'
          UnhealthyThreshold: '5'
          Interval: '30'
          Timeout: '5'
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-048f6ed62451373d9"
            InstanceType: "t2.micro"
            KeyName: "vockey"
            AvailabilityZone: "us-east-1a"
            SecurityGroups: 
            - Ref: EC2SecurityGroup
            Tenancy: "default"
            EbsOptimized: false
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/sda1"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 8
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            Tags: 
              - 
                Key: "Name"
                Value: "LAMP01"
            HibernationOptions: 
                Configured: false
            EnclaveOptions: 
                Enabled: false
    EC2Instance2:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-048f6ed62451373d9"
            InstanceType: "t2.micro"
            KeyName: "vockey"
            AvailabilityZone: "us-east-1b"
            SecurityGroups: 
            - Ref: EC2SecurityGroup2
            Tenancy: "default"
            EbsOptimized: false
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/sda1"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 8
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            Tags: 
              - 
                Key: "Name"
                Value: "LAMP02"
            HibernationOptions: 
                Configured: false
            EnclaveOptions: 
                Enabled: false
    EC2SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "securityGroupOne"
            GroupName: "securityGroupOne"
            SecurityGroupIngress: 
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 80
                IpProtocol: "tcp"
                ToPort: 80
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 22
                IpProtocol: "tcp"
                ToPort: 22
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 443
                IpProtocol: "tcp"
                ToPort: 443
    EC2SecurityGroup2:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "securityGroupTwo"
            GroupName: "securityGroupTwo"
            SecurityGroupIngress: 
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 80
                IpProtocol: "tcp"
                ToPort: 80
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 22
                IpProtocol: "tcp"
                ToPort: 22
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 443
                IpProtocol: "tcp"
                ToPort: 443
